#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2026 Simplyblock GmbH.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../..)

TEST_FILE = blob_md_journal_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
