FROM public.ecr.aws/docker/library/fedora:41

# push to "simplyblock/spdk-core:base_image"

USER root

WORKDIR /root

RUN dnf install -y git diffutils procps-ng pip kmod hostname wget pkg-config cmake nano systemd-udev openldap-clients  \
    dosfstools ntfsprogs e2fsprogs ntfs-* gdb parted fio xfsprogs libasan libubsan iptables  python3 python3-pip  \
    nvme-cli librdmacm-utils perftest numactl gdisk

COPY ./ /root/spdk/

RUN cd spdk && scripts/pkgdep.sh --rdma --pmem

RUN rm -rf /root/spdk


# Build OpenSSL
RUN dnf update -y && dnf upgrade -y && \
    dnf install -y zlib-devel make gcc perl curl \
    libcurl-devel libuuid-devel pulseaudio-libs-devel && \
    wget https://www.openssl.org/source/openssl-3.5.6.tar.gz && \
    tar -xvf openssl-3.5.6.tar.gz && \
    cd openssl-3.5.6 && \
    ./config && make -j"$(nproc)" && make install && \
    echo /usr/local/lib64 > /etc/ld.so.conf.d/openssl.conf && ldconfig && \
    cd .. && rm -rf openssl-3.5.6*

# Clone + build AWS SDK
RUN git clone --recurse-submodules https://github.com/simplyblock-io/aws-sdk-cpp && \
    touch aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/pthread_utils.h && \
    cp aws-sdk-cpp/pthread_utils.txt aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/pthread_utils.h && \
    mkdir -p aws-sdk-cpp/sdk_build && \
    cd aws-sdk-cpp/sdk_build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Debug \
    -DBUILD_SHARED_LIBS=OFF \
    -DFORCE_SHARED_CRT=OFF \
    -DUSE_CRT_HTTP_CLIENT=ON \
    -DCMAKE_PREFIX_PATH=/usr/local/ \
    -DCMAKE_INSTALL_PREFIX=/usr/local/ \
    -DENABLE_TESTING=OFF \
    -DBUILD_ONLY="s3;s3-crt" && \
    make -j"$(nproc)" && make install

RUN dnf clean all && rm -rf /var/cache/dnf /var/cache/yum

RUN rm -rf /root/aws-sdk-cpp/.git