FROM fedora:41

# push to "simplyblock/spdk-core:$TAG"

USER root

WORKDIR /root

COPY ./ /root/spdk/

RUN dnf install -y git diffutils procps-ng pip kmod hostname wget pkg-config cmake nano systemd-udev

RUN yum install -y dosfstools ntfsprogs e2fsprogs ntfs-* gdb parted fio xfsprogs libasan libubsan

RUN pip install requests

RUN cd spdk && git submodule update --init --depth 1

RUN cd spdk && scripts/pkgdep.sh --rdma --pmem

RUN mkdir /tmp/pmem

RUN sed -i "s/^#define SPDK_JSONRPC_RECV_BUF_SIZE.*/#define SPDK_JSONRPC_RECV_BUF_SIZE\t(2 * 1024 * 1024)/" /root/spdk/lib/jsonrpc/jsonrpc_internal.h

RUN sed -i "s/^#define SPDK_BDEV_QOS_MIN_IOS_PER_SEC.*/#define SPDK_BDEV_QOS_MIN_IOS_PER_SEC\t200/" /root/spdk/lib/bdev/bdev.c

RUN sed -i "s/^#define SPDK_BDEV_QOS_TIMESLICE_IN_USEC.*/#define SPDK_BDEV_QOS_TIMESLICE_IN_USEC\t5000/" /root/spdk/lib/bdev/bdev.c

RUN cd spdk && ./configure --with-crypto --with-rdma --disable-tests --disable-unit-tests --disable-examples --with-ocf --with-fuse\
     --with-nvme-cuse --target-arch=nehalem

RUN cd spdk && make CONFIG_DEBUG=y CONFIG_STRIP=n --no-builtin-rules -j16
