# syntax=docker/dockerfile:1.7

# ---------------------------------------------------------------------------
# Stage 1: builder
# ---------------------------------------------------------------------------
FROM public.ecr.aws/docker/library/fedora:41 AS builder

USER root

WORKDIR /root

RUN dnf install -y git diffutils procps-ng pip kmod hostname wget pkg-config cmake nano systemd-udev openldap-clients  \
    dosfstools ntfsprogs e2fsprogs ntfs-* gdb parted fio xfsprogs libasan libubsan iptables  python3 python3-pip  \
    nvme-cli librdmacm-utils perftest numactl gdisk zlib-devel make gcc perl curl \
    libcurl-devel libuuid-devel pulseaudio-libs-devel

# Build OpenSSL
RUN wget https://www.openssl.org/source/openssl-3.5.6.tar.gz && \
    tar -xvf openssl-3.5.6.tar.gz && \
    cd openssl-3.5.6 && \
    ./config && make -j"$(nproc)" && make install && \
    echo /usr/local/lib64 > /etc/ld.so.conf.d/openssl.conf && ldconfig && \
    cd .. && rm -rf openssl-3.5.6*

# Clone + build AWS SDK
RUN cd /root/ && git clone --recurse-submodules https://github.com/simplyblock-io/aws-sdk-cpp && \
    touch aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/pthread_utils.h && \
    cp aws-sdk-cpp/pthread_utils.txt aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/pthread_utils.h && \
    mkdir -p aws-sdk-cpp/sdk_build && \
    cd aws-sdk-cpp/sdk_build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Debug \
    -DBUILD_SHARED_LIBS=OFF \
    -DFORCE_SHARED_CRT=OFF \
    -DUSE_CRT_HTTP_CLIENT=ON \
    -DCMAKE_PREFIX_PATH=/usr/local/ \
    -DCMAKE_INSTALL_PREFIX=/usr/local/ \
    -DENABLE_TESTING=OFF \
    -DBUILD_ONLY="s3;s3-crt" && \
    make -j"$(nproc)" && make install


FROM public.ecr.aws/docker/library/fedora:41 AS runtime
WORKDIR /root

# Runtime OS packages only. Dropped from the original:
#   gdb, fio, perftest           -> debug/benchmark tools, not runtime
#   ntfs-*  (wildcard)           -> replaced with explicit ntfs-3g + ntfsprogs
# If any of these are actually needed in prod, add them back deliberately.
RUN dnf install -y git diffutils procps-ng pip kmod hostname wget pkg-config cmake nano systemd-udev openldap-clients  \
    dosfstools ntfsprogs e2fsprogs ntfs-* gdb parted fio xfsprogs libasan libubsan iptables  python3 python3-pip  \
    nvme-cli librdmacm-utils perftest numactl gdisk zlib-devel make gcc perl curl \
    && dnf clean all && rm -rf /var/cache/dnf /var/cache/yum


# Pull across the compiled artefacts from the builder.
COPY --from=builder /usr/local/                       /usr/local/
COPY --from=builder /etc/ld.so.conf.d/openssl.conf    /etc/ld.so.conf.d/openssl.conf